### ISSUE TITLE
Stored Transactions

### ISSUE THREAD

**Issue by tmayoff** [tmayoff/recurr#82]
# Description
I'd like to separate from plaid a little bit, so the plan should be to just sync the transactions to our own DB and track categories that way.

This needs:
- [x] #48 
- [x] #89
- [x] Setup DB tables
- [ ] Setup custom categories
- [ ] Match plaid with our own data
